os:
    - osx
language: generic
sudo: required

osx_image: xcode8.3
before_install:
    brew tap vapor/tap;
    brew update;
    brew install vapor;

script:
    - swift build
    - swift build -c release
    - swift test
